### ISSUE TITLE
Feature Request: Requirements

### ISSUE THREAD

**Issue by austin4195** [Pixelmon-Development/ForgeMenus#8]
### Premise of the idea

The main idea behind item requirements is to change how an item is displayed based on a set of requirements that can be provided.

### DeluxeMenus

Makes use of a priority system. The higher the number, the lower the priority. Here is an example of how it is implemented there (example is from my ranks menu on another server I run)

```
  'Player2 Ranks':
    material: light_gray_concrete
    data: 8
    slot: 11
    display_name: '&9&lSettler &8- &c&lLOCKED'
    lore:
      - '&aPerks:'
      - '&fBuy/Sell Claim Blocks'
      - '&f 2 Player Warps'
      - '&f100 Claim Blocks'
      - '&f'
      - '&aRequirements:'
      - '&f4 Hours Playtime'
      - '&f$10,000'
      - '1 Player Warp Created'
    priority: 10

  'Player1 Unlocked':
    material: lime_concrete
    data: 5
    slot: 9
    display_name: '&3&lSurvivor &8- &a&lUNLOCKED'
    lore:
      - '&aPerks:'
      - '&f2 Homes'
      - '&f100 Claim Blocks'
      - '&fCreate a Player Warp'
    priority: 3
    view_requirement:
      requirements:
        anythinghere:
          type: has permission
          permission: special.player1
          
  'Player1 Locked':
    material: red_concrete
    data: 14
    slot: 9
    display_name: '&3&lSurvivor &8- &c&lLOCKED'
    lore:
      - '&aPerks:'
      - '&f2 Homes'
      - '&f100 Claim Blocks'
      - '&fCreate a Player Warp'
      - '&aRequirements:'
      - '&f2 Hours Playtime'
      - '&f$4,000'
      - '&fDiscord Linked'
    priority: 5
    left_click_commands:
      - '[player] rankup'
      - '[close]'
    right_click_commands:
      - '[player] rankup'
      - '[close]'
```
      
In this example, the ranks menu shows the grayed out concrete until the rank in question is next. At this point, the player possesses the rank permission so it now displays the red concrete. Once they have ranked up to it, it will display the green concrete as they possess that permission. The downside to this method is it requires creating separate instances of the item and the plugin is to check the priority then requirement to determine which item should be displayed.

### VirtualChest

VC does this a bit differently. VC also has requirements but does not use a priority system instead saying "does the viewer meet the requirement outlined? No, fallback onto other item."

Example:

```
 Slot33 = [{
    Item {
      Count = 1
      ItemType = "pixelmon:lucky_egg"
      UnsafeDamage = 0
      DisplayName = "&a&lEggNav"
      ItemLore = [
	    "&f"
        "&f  &b Access the Daycare Dimension!"
        "&f"
        ]
		UnsafeData {
			tooltip=""
			}
	}
	Requirements = "player.hasPermission('group.trainer7')"
    PrimaryAction {
      Command = "sts"
      KeepInventoryOpen = false
	}
    },{
    Item {
      Count = 1
      ItemType = "pixelmon:lucky_egg"
      UnsafeDamage = 0
      DisplayName = "&c&lEggNav"
      ItemLore = [
	    "&f"
        "&f  &c EggNav allows you to access the Daycare Dimension!"
        "&f  &c Module has not been unlocked yet, Rank up to unlock!"
        "&f"
		  ]
        }
    }]
```

In this example, the slot has multiple items defined under it. VC also supports AND and OR operations for requirements so you could have more than one thing be required before display of the item.

### Proposed Implementation

Using the example menu that is generated, this is one way I can think of on how to implement this. The idea is that VC has it a bit simpler by not factoring in priority then requirement checking but rather just requirement checking.

```
    items:
        one:
            positionX: 0
            positionY: 0
            type: 447
            amount: 1
            name: This is an item name! §bBLUE
            lore: [§bLore line 1!, §bLore line 2!]
            commands: ['console:kill %forge_name%', 'console:ban %forge_name% Test!']
            requirement: ['permission: menusare.fun']
            else:
               type: 447
               amount: 1
               name: This is an item name! §bRED
               lore: [§bYou no meet requirement!]
               commands: []
```

This approach keeps it simple by defining the alternate item to display so if the requirement fails, it falls back on the else item. This also doesnt require defining the item position more than once (like DM) and attempts to maintain simplicity by keeping variants of the display item wrapped under the one grouping. Also, if requirement is null then the else is ignored.

This is of course open to modification but I figured I would take a crack at trying to come up with a way that's simple to implement and simple as a person making configs.
